name: Continuous Integration

on:
  push:
    branches:
      - orgin/UnitTest
  pull_request:
    branches:
      - orgin/UnitTest

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Restore NuGet Packages
      run: |
        cd D:\a\SchoolManagement\SchoolManagement\StudentManagement
        # Edit the .csproj file to add the PackageReference manually
        echo '<ItemGroup><PackageReference Include="MaterialDesignThemes" Version="4.8.0" /><PackageReference Include="MSTest.TestAdapter" Version="3.1.1" /></ItemGroup>' >> StudentManagement.csproj
        nuget restore StudentManagement.sln

    - name: Build
      run: |
        dotnet build StudentManagement.sln

    - name: Run Tests
      run: |
        dotnet test StudentManagementTests/StudentManagementTests.csproj

    - name: Install Stryker.NET
      run: |
        dotnet tool install -g dotnet-stryker

    - name: Mutation Testing
      run: |
        dotnet-stryker
